# Generated by Django 6.0.3 on 2026-03-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('non_verbal', 'Non-Verbal Reasoning'), ('verbal', 'Verbal Reasoning'), ('spatial', 'Spatial Reasoning'), ('mixed', 'Mixed')], max_length=20)),
                ('subtype', models.CharField(choices=[('sequence', 'Sequence'), ('rotation', 'Rotation'), ('odd_one_out', 'Odd One Out'), ('mirror', 'Mirror/Reflection'), ('hidden_shapes', 'Hidden Shapes'), ('letter_series', 'Letter Series'), ('word_code', 'Word Code'), ('number_pattern', 'Number Pattern'), ('letter_number', 'Letter-Number Code'), ('cube_faces', 'Cube Faces'), ('nets', 'Nets'), ('rotation_3d', '3D Rotation'), ('block_counting', 'Block Counting')], max_length=30)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('answer', models.CharField(max_length=200)),
                ('explanation', models.TextField()),
                ('technique', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['type', 'difficulty', 'id'],
            },
        ),
    ]
